### PR TITLE
Add Simplified Chinese (abbr. zh) Translation

### PR DESCRIPTION
**Pull request by doctormin**
Thanks for creating this great book!

This is a WIP PR for adding zh translation.

### CODE REVIEW

**Comment by 777arc** [comment]
should the 2-letter code be ZH or CN?  https://en.wikipedia.org/wiki/ISO_3166-2:CN#:~:text=The%20first%20part%20is%20CN,alpha%2D2%20code%20of%20China.

I made the Ukranian one xyz-ukraine because their 2-letter code is UA but I figure a lot of folks wont know that, and I don't want people to be confused about which directory is which

**Comment by doctormin** [comment]
While Chinese is used across many countries and regions, it can be divided into Simplified Chinese and Traditional Chinese. For the Simplified Chinese version of my translation, you can use either "zh" or "zh-CN"; both are standard language codes. as long as everyone can understand it, it's fine. You can decide on the specifics :)

**Comment by 777arc** [comment]
Ah ok.  I just pushed some changes, you should now be able to run `make html-zh` and then open _build/zh/index-zh.html to preview the textbook (the Chinese flag at the top isnt going to show up till after we merge into main).  In the Makefile on line 88 where it says project=".." you can feel free to translate that

**Comment by 777arc** [comment]
If you want I can finish up and merge this PR, we don't have to do every chapter in the first PR, what do you think?

**Comment by doctormin** [comment]
Sure! I am of course thrilled to see the official launch of the Chinese version as long as you agree with the WIP status

**Pull request merged**
